# ========================================
# 애플리케이션 기본 설정
# ========================================

spring:
  application:
    # 프로젝트 이름 설정 (로깅/모니터링 시 애플리케이션 이름으로 표시)
    name: springboot-quickstart-study

  main:
    # 웹 애플리케이션 타입 설정
    # - servlet: 스프링 MVC 기반 웹 서버(Tomcat)로 실행
    # - reactive: 스프링 WebFlux 기반 비동기/논블로킹 리액티브 웹 서버로 실행
    # - none: 웹 서버 없이 일반 자바 프로그램처럼 실행
    web-application-type: servlet

    # 배너 출력 위치 설정
    # - console: 콘솔 출력 (기본값)
    # - log: 로거를 통해 출력
    # - off: 출력 안 함
    banner-mode: console

  banner:
    # 텍스트 배너 커스터마이징 경로
    # location: banner/banner.txt

    # image:
      # 이미지 배너 커스터마이징 경로
      # location: banner/spring_boot.png
      # 이미지 배너 출력 시 너비 설정
      # width: 80
      # 이미지 배너 출력 시 높이 설정
      # height: 10

# ========================================
# 서버 설정
# ========================================

server:
  # 내장 톰캣 서버 포트 번호 설정 (기본값: 8080)
  # 포트를 0으로 설정하면 사용 가능한 포트 중 하나가 자동 할당
  port: 8000