# ========================================
# 애플리케이션 기본 설정
# ========================================

spring:
  application:
    # 애플리케이션 이름 (로깅 및 모니터링용)
    name: springboot-quickstart-study

  main:
    # 웹 애플리케이션 타입 설정
    # servlet : Spring MVC (기본값, Tomcat 기반)
    # reactive : Spring WebFlux (비동기/논블로킹)
    # none : 웹 서버 없이 실행
    web-application-type: servlet

    # 배너 출력 모드
    # console : 콘솔에 출력 (기본값)
    # log : 로거를 통해 출력
    # off : 비활성화
    banner-mode: console

    # 동일한 Bean 이름이 있을 경우 덮어쓰기 허용 여부
    allow-bean-definition-overriding: true

  # ViewResolver Setting
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  banner:
    # 커스텀 텍스트 배너 파일 경로
    # location: ch1/banner/banner.txt

    # 커스텀 이미지 배너 파일 경로
    # image:
      # location: ch1/banner/spring_boot.png
      # width: 80
      # height: 10

  datasource:
    # H2 데이터베이스 드라이버 설정
    driver-class-name: org.h2.Driver

    # H2 DB 접속 URL(웹 애플리케이션과 툴에서 동시 접속 가능하도록 설정)
    url: jdbc:h2:C:/Users/gusun/test;AUTO_SERVER=TRUE

    # 사용자명
    username: sa

    # 비밀번호
    password: ""

  jpa:
    # Hibernate 동작 관련 설정
    hibernate:
      # 테이블 자동 생성 전략
      # create : 기존 테이블 삭제 후 재생성
      # update : 변경된 부분만 반영
      # none   : DDL 생성 및 실행 안함
      ddl-auto: update

    # Spring JPA가 DDL을 생성할지 여부
    generate-ddl: false

    # 실행되는 SQL을 콘솔에 출력
    show_sql: true

    # Hibernate DB 방언 설정
    database-platform: org.hibernate.dialect.H2Dialect

    properties:
      hibernate:
        # SQL 문을 보기 좋게 포맷하여 출력
        format_sql: true

# ========================================
# 로깅 설정
# ========================================

logging:
  level:
    # 전체 애플리케이션 기본 로그 레벨
    root: info

    # Hibernate SQL 실행 로그 레벨
    org.hibernate: info

    # com.example.springbootquickstartstudy 패키지 이하 로그 레벨
    # com.example.springbootquickstartstudy: debug

    # file:
    # 로그 파일 경로 설정
    # name: src/main/resources/ch3/logs/board_log.log

# ========================================
# 서버 설정
# ========================================

server:
  # 내장 톰캣 포트 (기본값 8080)
  # 0으로 설정하면 사용 가능한 포트 자동 할당
  port: 8080

# ========================================
# 데이터베이스 설정 (Oracle)
# ========================================

board:
  jdbc:
    # Oracle 드라이버 클래스
    driverClass: oracle.jdbc.driver.OracleDriver

    # Oracle DB 접속 URL
    url: jdbc:oracle:thin:@localhost:1521:XE

    # Oracle 사용자명
    username: JY

    # Oracle 비밀번호
    password: 4001

# ========================================
# 테스트용 프로퍼티
# ========================================
author:
  # 작성자 이름
  name: YJY

  # 작성자 나이
  age: 2626